"""empty message

Revision ID: 39781666eff8
Revises: 3ee82fc34eec
Create Date: 2016-02-01 17:29:30.632150

"""

# revision identifiers, used by Alembic.
revision = '39781666eff8'
down_revision = '3ee82fc34eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
