"""empty message

Revision ID: da85cbf692b
Revises: 39781666eff8
Create Date: 2016-02-01 19:27:19.173299

"""

# revision identifiers, used by Alembic.
revision = 'da85cbf692b'
down_revision = '39781666eff8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
